# Generated by Django 5.0.6 on 2024-07-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_order_created_at'),
        ('product', '0005_alter_product_chocolate_alter_product_coffee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='latte', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='product.product'),
        ),
    ]
