# Generated by Django 5.0.6 on 2024-06-26 00:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Vertical',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('sugar', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('coffee', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('flour', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('chocolate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.vertical')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
