# Generated by Django 5.0.6 on 2024-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chocolate',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='coffee',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='flour',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.IntegerField(max_length=10),
        ),
    ]
