# Generated by Django 5.0.6 on 2024-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_chocolate_alter_product_coffee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chocolate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='coffee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='flour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.IntegerField(),
        ),
    ]
