# Generated by Django 4.2.13 on 2024-07-02 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_storage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Storage",
        ),
    ]
